assignmentObjects = Deque RandomizedQueue
testObjects = Deque RandomizedQueue
assignmentName = queues

include ../algs4.mk

Deque.test: Deque.class DequeTest.class
	$(JUNIT) DequeTest

RandomizedQueue.test: RandomizedQueue.class RandomizedQueueTest.class
	$(JUNIT) RandomizedQueueTest
