assignmentObjects = Percolation PercolationStats
otherObjects = PercolationVisualizer
assignmentName = percolation

include ../algs4.mk

test: Percolation.class
	java -classpath ./:../stdlib.jar:../algs4.jar Percolation
