assignmentObjects = Percolation PercolationStats
testObjects = Percolation PercolationStats
otherObjects = PercolationVisualizer
assignmentName = percolation

include ../algs4.mk

PercolationStats.test: PercolationStats.class
	$(JAVA) PercolationStats 1024 100
