assignmentObjects = PointSET KdTree
otherObjects = RectHV NearestNeighborVisualizer RangeSearchVisualizer
testObjects = PointSET KdTree
assignmentName = kdtree

include ../algs4.mk

PointSET.test: PointSET.class RectHV.class PointSETTest.class
	$(JUNIT) PointSETTest

KdTree.test: KdTree.class RectHV.class KdTreeTest.class
	$(JUNIT) KdTreeTest

