assignmentObjects = PointSET
otherObjects = RectHV
testObjects = PointSET
assignmentName = 

include ../algs4.mk

PointSET.test: PointSET.class RectHV.class PointSETTest.class
	$(JUNIT) PointSETTest

