assignmentObjects = WordNet SAP #Outcast
otherObjects = 
testObjects = WordNet SAP
assignmentName = kdtree

include ../algs4.mk

WordNet.test: WordNet.class SAP.class WordNetTest.class
	$(JUNIT) WordNetTest

SAP.test: SAP.class SAPTest.class
	$(JUNIT) SAPTest

