assignmentObjects = WordNet #SAP Outcast
otherObjects = 
testObjects = WordNet #SAP
assignmentName = kdtree

include ../algs4.mk

WordNet.test: WordNet.class WordNetTest.class
	$(JUNIT) WordNetTest


